name: SvarttMovementPlugin
version: '2.0.1'
main: me.hatesvartt.svarttMovementPlugin.SvarttMovementPlugin
api-version: '1.21'
authors: [ hatesvartt ]
description: Sets a max for Elytra Speed, Flying and on-ground Movement Hacks while not touching vanilla movements
folia-supported: true
